### ISSUE TITLE
Changing the background color does not work.

### ISSUE THREAD

**Issue by bramvbilsen** [santomegonzalo/react-electron-titlebar#2]
It seems like the `backgroundColor` property does not function properly. The background is always black.  
Code snippet:
```jsx
<Titlebar title="Invoice Manager" backgroundColor="#ffffff" />
``` 
I'd expect the background to be white in this case, but it remains black.

**Comment by santomegonzalo** [comment]
I will take a look into this... thanks for reporting it!

**Comment by Conji** [comment]
@santomegonzalo this is fixed by wrapping `${props => props.backgroundColor}` in quotation marks. Tested and confirmed it works. I'd submit a PR, but it's something so small that it'd probably be easier fixed by just notifying you. Also, `componentWillUnMount` is supposed to have a lowercased "m" in "unmount" (not sure if this'll actually affect lifecycle events)

**Comment by aabbccsmith** [comment]
This PR will fix it: https://github.com/santomegonzalo/react-electron-titlebar/pull/3

**Comment by santomegonzalo** [comment]
I will release the fix in about an hour... Thabks

**Comment by aabbccsmith** [comment]
Hi there,

I noticed that the new version wasn't published on `npm`. Any idea when it will be?

Many thanks

**Comment by santomegonzalo** [comment]
Hi @aabbccsmith  I just pushed the changes on version `1.0.9`

https://www.npmjs.com/package/react-electron-titlebar

**Comment by alii** [comment]
Works perfectly, thanks!
